name: emoticare_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.2
  http: ^1.2.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  percent_indicator: ^4.2.3
  model_viewer_plus: ^1.7.0
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
